// Automatically generated by Interoptopus.

#pragma warning disable 0105
using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using PermissionLib;
#pragma warning restore 0105

namespace PermissionLib
{
    public static partial class Permission
    {
        public const string NativeLib = "permission_lib";

        static Permission()
        {
        }


        /// Function using the type.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "init")]
        public static extern bool init(ref string policies, ref string schema);

        /// Function using the type.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "clean")]
        public static extern bool clean();

        /// Function using the type.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "check")]
        public static extern bool check(ref string policies, ref string schema, ref string principal, ref string action, ref string resource, ref string context, ref string entities);

    }



    public class InteropException<T> : Exception
    {
        public T Error { get; private set; }

        public InteropException(T error): base($"Something went wrong: {error}")
        {
            Error = error;
        }
    }

}
