[package]
name = "permission_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cedar-policy = { version = "3.1.3", features = [ "partial-eval" ] }
interoptopus = "0.14.23"
interoptopus_backend_csharp = "0.14.24"
serde_json = "1.0"
